language: php

php:
  - 7.2

services:
  - mysql

before_script:
  - cp .env.travis .env
  - mysql -e 'create database test;'
  - composer self-update
  - composer install --no-interaction
  - npm install
  - gunzip test_db.sql.gz
  - mysql -u root test < test_db.sql
  - php artisan migrate --seed
  - php artisan key:generate
  - php artisan config:clear
  - npm run prod
  - composer require --dev phpcq/all-tasks
  - vendor/bin/phpcpd
